---
abstract: unknown
author:
  - 'Mischa Spiegelmock <revmischa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyMQ-RawSocket
no_index:
  directory:
    - t
    - inc
requires:
  Any::Moose: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  AnyMQ: 0
  JSON: 0
  Test::More: 0
version: 0.02
